[json] roll keyword
codesquad-members-2021/fe-w5-searchUI pull request #19
Opened 2021-03-09 09:50 UTC by kowoohyuk

> ## 구현 기능
> > * [x]  인기 검색어 data 요청
> > * [x]  인기 검색어 출력
> > * [x]  roll 애니메이션 구현

상단 검색창의 roll 태그를 작성했습니다.  
클라이언트에서  서버로 미리 준비해둔 json 값을 요청하고, 반환 받은 값을 렌더링 합니다.  
애니메이션은 transition을 설정한 상태에서 상단으로 transform 처리를 하였고, 
이후 transition을 제거한 뒤, 원 위치로 transform 및 태그의 위치 변경을 발생하도록 처리했습니다.

2021-03-09 13:20 UTC, merged

2021-03-09 15:01 UTC, P-iknow requested changes
안녕하세요, 이번에 리뷰어로 참여하게된 셀데브라고 합니다. 앞으로 종종 리뷰로 뵙게 될 것 같네요.
일단 과제하느라 너무 고생 많으십니다. 응원합니다 🙏 🙏 

제가 리뷰에 남긴 p2, p3 등의 의미는 [리뷰를 위한 제언](https://www.notion.so/piknow/14c13a62a4b24e72856cbac2fb70621e) 을 참고 부탁드리겠습니다. 

전반적으로 의도를 더 드러내주셨으면 합니다. 의도를 드러내는 방법으로 함수 추출이 있습니다. 
의도를 드러내는 방법이 모호할 수 있는데, 어떤 처리를 하는 부분에 대해 어떤 일을 하는지 주석으로 달아봅니다.  주석으로 달아보면 그  부분이 무슨일을 하는지가 드러납니다, 그럼 그 주석을 기반으로 함수를 만듭니다. 
이렇게 의도가 드러난 함수가 추출됩니다. 

 
또한 함수의 역할을 더 잘개 쪼개보시면 좋을 거 같아요. 이 부분은 작성하신 함수를 테스트해보고자 할때 어떤 부분을 검증해야하는지 생각해보는 것 입니다. 검증해야 하는게 너무 많거나, 검증이 어렵다면 그게 바로 함수가 너무 많은 역할을 하고 있다는 시그널입니다. 

한번 더 고민해주시길 부탁드립니다. 제가 남겼던 질문에 의문이 댓글로 남겨주시거나 슬랙에서 seldev 로 dm 주셔도 됩니다. 

부탁드려요 🙏 
-  PR body에 리뷰가 더 필요한 부분이 있으면 그 부분을 더 집중적으로 볼 수 있을 것 같습니다.
-  PR body에 작성하신 부분을 어떻게 실행할 수 있는지 안내해주신다면 더 잘 리뷰할 수 있을 것 같습니다. 
-  PR body에 완성화신 화면을 보여주시면 리뷰어의 이해에 도움이 될 것 같습니다.

2021-03-10 09:30 UTC, kowoohyuk commented on main.js
> +  }
넵! 공통 로직을 분리하고 함수의 역할을 축소시켜서 명확하게 구분이 가능하도록 아래처럼 나눠보겠습니다!
handleMove - 공통 로직
 |
 -- movePrev, moveNext - 분기

2021-03-10 09:34 UTC, kowoohyuk commented on main.js
> +      }
break가 없는데 왜 fotEach를 안했을까요?!
말씀해주신 리뷰대로 수정하겠습니다!

2021-03-10 09:37 UTC, kowoohyuk commented on main.js
> +  });
> p2; 이 부분도 바로 함수표현식으로 작성되다 보니 함수 이름으로 부터 어떤 역할을 하는지 힌트를 얻을 수가 없네요.
> 함수 이름으로 힌트를 부탁드려봅니다 🙏
> 
> * 이 함수 하나가 너무 많은 역할을 하고 있는거 같은데 쪼개보시면 어떨까요?

저도 제 코드를 보면서 각각의 함수가 너무 혹사당한다는 생각을 했었는데 정말 나쁜 습관인거 같습니다. 짧으면서 한 눈에 파악이 가능한 함수로 고치도록 하겠습니다!

2021-03-10 09:37 UTC, kowoohyuk commented on main.js
> +      }
> p2;
> for 문은 i 의 활용으로 인해 사람이 실수할 여지를 줄 수 있죠. 우리에게는 배열 method 들이 있습니다. 그것을 사용해보시면 어떨까요? 이런 상황(사이드 effect - 배열을 순회해서 특정 값을 리턴하지 않고, 뭔가 다른일을 하는 상황) 에서는 forEach 메소들 쓰면 좋을 것 같네요.
> 
> ```js
> list.forEach((item) => {
>   if (item.classList.contains('active')) {
>     activeIndex = i;
>   }
>   if (item === target) {
>     targetIndex = i;
>   }
> });
> ```

break가 없는데 왜 fotEach를 안했을까요?!
말씀해주신 리뷰대로 수정하겠습니다!

2021-03-10 09:40 UTC, kowoohyuk commented on main.js
> +    if(data) setTotalBoxCount(data.length);
> p4;
> else case도 고려해주시면 좋겠네요

else일 때, 기본 값을 전달하거나 data 자체에 기본값을 주는 방법으로 예외처리 하겠습니다!

2021-03-10 09:43 UTC, kowoohyuk commented on main.js
> +  const getBox = async () => {
> p2;
> `getBox` 라는 함수명으로 유추해보면 사용하는 쪽에서는 box를 리턴할 것 처럼 보이는데,
> return 하지 않고 내부에서 다른 함수를 실행시키고 있네요? 다른 이름을 고려해주시면 어떻까요?
> api 를 호출한 뒤에 무언가를 하는 로직은 이 함수를 쓰는 곳으로 꺼내주시는게 더 좋을 것 같아요.

리뷰를 읽고나니 확실히 함수명과 행위가 전혀 연관없는 처리를 하고 있었네요.
감사합니다!
getBox를 반환을 위한 코드로 재작성하거나 함수명을 변경토록 하겠습니다.

2021-03-10 11:09 UTC, kowoohyuk commented on api.js
> +}
> p2; 이번 미션의 조건의 promise 안쓰기로 알고 있습니다.
> 
> fetch 가 반환하는 값은 promise 입니다. 뒤에 `then` able 한 코드들이 이어지는 것을 보면 알수 있죠.
> async await 을 써서 바꿔보면 어떨까요?
> 
> 바꾸실 때 `.catch` 부분을 잘 고려하시면 좋을 것 같습니다. 해당 패턴을 아주 많이 사용하니 연습해두시면 좋습니다.
> `Hint:` try catch 구문

조건에 맞지 않게 then 을 사용하고 있었네요!
async, await로 바꾸면서 에러 처리도 트라이 캐치 구문을 적절히 활용하도록 하겠습니다!

2021-03-10 11:10 UTC, kowoohyuk commented on main.js
> +  }
> p3;
> check 라는 prefix는 마치 boolean (true or false)연상시키는데, 이 함수가 하는일을 주석으로 달아보고, 그 주석을 통해 다시 이름을 지어보는 건 어떠세요. 일단 길어도 좋으니깐요.

먼저 두 개의 함수 (isAble, handle)로 나눈 이후 하나로 합칠 방법을 생각해보겠습니다!
이름 짓기가 정말 힘드네요 ㅠ_ㅠ

2021-03-10 11:11 UTC, kowoohyuk commented on main.js
> +    if(data) renderTheme(data);
> p3;
> 위에서 말씀드렸던 부분과 같은 맥락입니다.
> api 호출하고 그 데이터를 받아 render 하는 곳은 getThem을 사용하는 곳에 노출시키는게 좋을 것 같습니다.
> 사용하는 쪽에서는 getTheme 만 보고는 어떤 일이 일어날지 알 수 없을 것 같습니다. 함수로 추출하신다면
> 그 역할이 분명해야 하고 하나의 역할만 하는게 좋습니다.

위의 getBox와 같이 코드를 재작성하거나 이름을 변경하여 역할을 명확히 파악할 수 있게 고치겠습니다!

2021-03-10 11:12 UTC, kowoohyuk commented on scss/header.scss
> +        &__image-span {
> fyi(for your information); scss 가 중첩이 된다 하더라도, 3번이상 중첩하면 가독성이 떨어져서 일부러 빼서 쓰기도 합니다.

indent가 너무 발생하는게 아닌가 싶었는데... 좋은 의견 감사합니다! 적당하게 3번 이내로 조절하겠습니다!

2021-03-10 11:13 UTC, kowoohyuk commented on server/server.js
> +});
> p4 요렇게 해보는 것도 좋아보이네요.
> 
> ```
> switch (true) {
>  case type === 'event' : 
>  case type === 'carousel':
> }
> ```

스위치문을 사용하거나 적절한 처리를 해서 분기를 좀 깔끔하게 수정해야겠어요!
저 부분이 라인이 너무 길어지는 느낌이었는데 역시 수정이 필요한거 같습니다.

2021-03-10 11:15 UTC, kowoohyuk commented
> 안녕하세요, 이번에 리뷰어로 참여하게된 셀데브라고 합니다. 앞으로 종종 리뷰로 뵙게 될 것 같네요.
> 일단 과제하느라 너무 고생 많으십니다. 응원합니다 🙏 🙏
> 
> 제가 리뷰에 남긴 p2, p3 등의 의미는 [리뷰를 위한 제언](https://www.notion.so/piknow/14c13a62a4b24e72856cbac2fb70621e) 을 참고 부탁드리겠습니다.
> 
> * 전반적으로 의도를 더 드러내주셨으면 합니다. 의도를 드러내는 방법으로 함수 추출이 있습니다.
>   의도를 드러내는 방법이 모호할 수 있는데, 어떤 처리를 하는 부분에 대해 어떤 일을 하는지 주석으로 달아봅니다.  주석으로 달아보면 그  부분이 무슨일을 하는지가 드러납니다, 그럼 그 주석을 기반으로 함수를 만듭니다.
>   이렇게 의도가 드러난 함수가 추출됩니다.
> * 함수의 역할을 더 잘개 쪼개보시면 좋을 거 같아요. 이 부분은 작성하신 함수를 테스트해보고자 할때 어떤 부분을 검증해야하는지 생각해보는 것 입니다. 검증해야 하는게 너무 많거나, 검증이 어렵다면 그게 바로 함수가 너무 많은 역할을 하고 있다는 시그널입니다.
> * main.js 내부의 init 함수안에서 모든 일이 발생하고 있는데요. 이 부분도 어떻게 하면 모둘화해서 쪼갤 수 있을지 생각해보셔도 좋을 것 같습니다.
> * 이번 리뷰에서 prototype 기능을 적극 쓰라고 권장되는 거 같은데,  prototype을 활용해서 같은 데이터를 사용하는 부분 끼리 응집해주고, 역할을 나누어주면 더 좋은 코드가 될 것 같아요
> 
> 한번 더 고민해주시길 부탁드립니다. 제가 남겼던 질문에 의문이 댓글로 남겨주시거나 슬랙에서 seldev 로 dm 주셔도 됩니다.
> 
> 부탁드려요 🙏
> 
> * PR body에 리뷰가 더 필요한 부분이 있으면 그 부분을 더 집중적으로 볼 수 있을 것 같습니다.
> * PR body에 작성하신 부분을 어떻게 실행할 수 있는지 안내해주신다면 더 잘 리뷰할 수 있을 것 같습니다.
> * PR body에 완성화신 화면을 보여주시면 리뷰어의 이해에 도움이 될 것 같습니다.

상세한 리뷰 정말 감사합니다!
저도 제 코드를 설명할 때, 명확하지 않은 부분이 많다고 생각만 하고 있었지
어떻게 수정할지 방향성에 대해서는 매번 고민이 있었고, 귀찮다는 생각으로 넘어가고만 있었는데
이렇게 상세하게 리뷰를 받게되니 바로 고쳐야겠다는 생각이 드네요!

의도가 명확히 드러나는 코드를 만들 수 있도록 얼른 수정하도록 하겠습니다!